config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'welcome#index'
  get 'users/my_portfolio'
  get 'stocks/search_stocks'
  get 'welcome/ajax'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :user_stocks
     has_many :stocks
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search_stocks

          @stock = StockQuote::Stock.quote(params[:stock])
          respond_to do |format|
            format.js {render partial: 'layouts/result'}
          end

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 def my_portfolio

 end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @user = User.all
  end
  def ajax
    @ajax = User.create(comments: "like this shit!!")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_ajax_commentbox.html.erb
<% form_for @ajax do |f|%>
  <%= f.text_area :comment, params[:comment], rows: '10' %>
  <%= f.submit :submit %>
<% end %>

app/views/layouts/_result.html.erb
<div class="container">
  <% if params[:stock].nil? and @stock.nil? %>
    <h6 id="empty_alert">Field should be neither blank nor filled with invalid stock names</h6>
  <% else %>
    <div class="container stocks_with_border">
      <b>NAME:</b> <%= @stock.name %> |
      <b>SYMBOL:</b> <%= @stock.symbol %> |
      <b>LAST PRICE:</b> <%= @stock.l %> |
      <b>EXCHANGE:</b> <%= @stock.exchange %> |
      <b>HIGH:</b> <%= @stock.hi %> |
      <b>LOW:</b> <%= @stock.lo %>
    </div>
   <% end %>
</div>

app/views/layouts/_result.js.erb
$("#results").html("<%= j (render 'layouts/result.html') %>")

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StocksTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
     <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/users/my_portfolio.html.erb
<div class="container">
  <div class="container greet">
    <h2>Lookup stocks here!!!</h2>
  </div><br>
  <div class="container">
    <%= form_tag stocks_search_stocks_path,remote: true, method: :get do %>
       <div class="col-lg-6">
         <div class="input-group">
           <%= text_field_tag :stock , params[:stock], autocomplete: "off", class: "form-control", placeholder: "Search Stocks.." %>
           <span class="input-group-btn">
             <%= submit_tag "Look for stocks" , class:"btn btn-secondary" %>
           </span>
         </div><br>
       </div>
    <% end %><br>
    <div id="results">
      <%= render 'layouts/result' %><br>
    </div>
  </div>
  <%= link_to "Back to home", root_path %>
</div>

app/views/welcome/ajax.html.erb
<div class="container">
  <h1>Ajax comment box!!!</h1>
  <%= render 'layouts/ajax_commentbox' %>
</div>

app/views/welcome/index.html.erb
<div class="container" align="center">
  <h1>New stocks-tracker app</h1>
  <% if !user_signed_in? %>
   <%= link_to "SIGNUP", new_user_registration_path %>
  <%  end %>
  <% if user_signed_in? %>
   <%= link_to "LOGOUT", destroy_user_session_path, method: :delete %> |
   <%= link_to "Search Stocks", users_my_portfolio_path %>
  <%  end %><br>
</div>